apiVersion: db.robert-sjoblom.dev/v1alpha1
kind: PostgresCluster
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: postgrescluster-sample
spec:
  # TODO(user): Add fields here
